version: '3.8'

services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge