version: '3.3'

services:
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Maps port 80 of the container to port 80 on the host
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
