version: '3.3'

services:
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
